version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: backend/.env.production
    expose:
      - 5000
    ports:
      - 5050
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - backend
