version: 2.1
jobs:
  frontend-code-quality-check:
    description: Run TypeScript type-checker on frontend
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dependencies-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
            - frontend-dependencies-{{ .Branch }}-
            - frontend-dependencies-
      - run: cd frontend && yarn install
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dependencies-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      # run typescript compiler
      - run: cd frontend && yarn tsc
      # run linter
      - run: cd frontend && yarn lint
      # run tests
      - run: cd frontend && yarn test
  deploy-frontend:
    description: Deploy frontend to firebase hosting
    docker:
      - image: circleci/node:jessie-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to Firebase
          command: |
            cd frontend
            yarn
            yarn build:stage
            ./node_modules/.bin/firebase use default
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting
            cd ../
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - frontend-code-quality-check
      - deploy-frontend:
          requires:
            - frontend-code-quality-check
          filters:
            branches:
              only: master
