name: CD
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Build frontend
        env:
          STAGING_FIREBASE_ADMIN_SDK_CONTENTS: ${{ secrets.STAGING_FIREBASE_ADMIN_SDK_CONTENTS }}
        run: |
          echo $STAGING_FIREBASE_ADMIN_SDK_CONTENTS > functions/src/firebase-adminsdk.json
          yarn workspace frontend build:stage
      - name: Deploy Frontend to Firebase Staging Project
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          ./node_modules/.bin/firebase use default
          ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting
      - name: Deploy Functions to Firebase Staging Project
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./deploy-functions $FIREBASE_TOKEN default
