name: CI Functions
on:
  push:
    paths:
      - '.github/workflows/ci-functions.yml'
      - 'common/**'
      - 'functions/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Create Dummy Files
        run: echo "{}" > functions/src/firebase-adminsdk.json
      - name: Run TypeScript Compiler
        run: yarn workspace functions tsc
