name: CI Frontend
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Run TypeScript Compiler
        run: yarn workspace frontend tsc
      - name: Build frontend
        run: PUBLIC_URL="/${{ github.event.number }}" yarn workspace frontend build:stage
      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-frontend-assets
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Built Static Assets
        uses: actions/download-artifact@master
        with:
          name: built-frontend-assets
          path: ${{ github.event.number }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PUBLISH_DIR: '.'
          PUBLISH_BRANCH: gh-pages
          PERSONAL_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        with:
          keepFiles: true
      - name: Comment on pull request
        uses: cornell-dti/dti-repo-tools@master
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
        with:
          command: pr-comment
          argument: '[deployment-bot] Deployed to https://staging-pr.samwise.today/${{ github.event.number }}/index.html'
