name: CI Frontend
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Run TypeScript Compiler
        run: yarn workspace frontend tsc
      - name: Run Tests
        run: yarn workspace frontend test
      - name: Build frontend
        run: PUBLIC_URL="/${{ github.event.number }}" yarn workspace frontend build:stage
      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-frontend-assets
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Built Static Assets
        uses: actions/download-artifact@master
        with:
          name: built-frontend-assets
          path: ${{ github.event.number }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PUBLISH_DIR: '.'
          PUBLISH_BRANCH: gh-pages
          PERSONAL_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        with:
          keepFiles: true
      - name: Comment on Pull Request
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              owner: 'cornell-dti',
              repo: 'samwise',
              issue_number: ${{ github.event.number }},
              body: 'Deployed to https://staging-pr.samwise.today/${{ github.event.number }}/index.html'
            });
