name: CI Frontend
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Run TypeScript Compiler
        run: yarn workspace frontend tsc
      - name: Build frontend
        run: yarn workspace frontend build:stage
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.STAGING_FIREBASE_ADMIN_SDK_CONTENTS }}'
          projectId: samwise-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
