name: CI
on: pull_request

jobs:
  enforce-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Print base ref and head ref
        run: |
          echo "Your head ref is ${{ github.head_ref }}."
          echo "Your base ref is ${{ github.base_ref }}."
      - name: Fail if try to push release from non-master branch
        if: github.base_ref != 'release' && github.head_ref == 'master'
        run: |
          echo "Head ref must be master for release. Everything should go through staging first!"
          exit 1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: cd frontend && yarn install
      - name: Run TypeScript Compiler
        run: cd frontend && yarn tsc
      - name: Run Linter
        run: cd frontend && yarn lint
      - name: Run Tests
        run: cd frontend && yarn test
      - name: Build frontend
        run: |
          cd frontend
          PUBLIC_URL="/${{ github.event.number }}" yarn build:stage
      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-frontend-assets
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Built Static Assets
        uses: actions/download-artifact@master
        with:
          name: built-frontend-assets
          path: ${{ github.event.number }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PUBLISH_DIR: '.'
          PERSONAL_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        with:
          keepFiles: true
      - name: Comment on Pull Request
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              owner: 'cornell-dti',
              repo: 'samwise',
              issue_number: ${{ github.event.number }},
              body: 'Deployed to https://staging-pr.samwise.today/${{ github.event.number }}/index.html'
            });
