name: CI
on: pull_request

jobs:
  enforce-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Print refs
        run: |
          echo "Your base ref is ${{ github.base_ref }}."
          echo "Your ref is ${{ github.ref }}."
      - name: Fail if try to push release from non-master branch
        if: github.base_ref != 'ref/head/master' && github.ref == 'ref/head/release'
        run: |
          echo "Base ref must be master. Everything should go through staging first!"
          exit 1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: cd frontend && yarn install
      - name: Run TypeScript Compiler
        run: cd frontend && yarn tsc
      - name: Run Linter
        run: cd frontend && yarn lint
      - name: Run Tests
        run: cd frontend && yarn test
      - name: Build frontend
        run: |
          cd frontend
          PUBLIC_URL="/${{ github.event.number }}" yarn build:stage
      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-frontend-assets
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout gh-pages Branch
        uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: Purge Old Static Assets
        run: git rm -rf ${{ github.event.number }} || echo "Nothing to remove"
      - name: Download Built Static Assets
        uses: actions/download-artifact@master
        with:
          name: built-frontend-assets
          path: ${{ github.event.number }}
      - name: Commit and Push New Static Assets
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        run: |
          git config user.name "deployment-bot"
          git config user.email "hello@cornelldti.org"
          git add .
          git commit -m "Deploy for ${{ github.event.number }}" || echo "Nothing to commit."
          git push "https://${ACCESS_TOKEN}@github.com/cornell-dti/samwise.git" || echo "Nothing to push."
      - name: Comment on Pull Request
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              owner: 'cornell-dti',
              repo: 'samwise',
              issue_number: ${{ github.event.number }},
              body: 'Deployed to https://staging-pr.samwise.today/${{ github.event.number }}/index.html'
            });
