name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: cd frontend && yarn install
      - name: Run TypeScript Compiler
        run: cd frontend && yarn tsc
      - name: Run Linter
        run: cd frontend && yarn lint
      - name: Run Tests
        run: cd frontend && yarn test
      - name: Build main-site-frontend
        run: |
          cd frontend
          PUBLIC_URL="/${{ github.event.number }}" yarn build:stage
      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-frontend-assets
          path: frontend/build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout gh-pages Branch
        uses: actions/checkout@master
        with:
          token: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
          ref: gh-pages
      - name: Purge Old Static Assets
        run: rm -rf ${{ github.event.number }}
      - name: Download Built Static Assets
        uses: actions/download-artifact@master
        with:
          name: built-frontend-assets
          path: ${{ github.event.number }}
      - name: Commit and Push New Static Assets
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
        run: |
          git config --global user.name "deployment-bot"
          git add .
          git commit -m "Deploy for ${{ github.event.number }}"
          git push "https://${ACCESS_TOKEN}@github.com/cornell-dti/samwise.git"
      - name: Comment on Pull Request
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
          script: |
            octokit.pulls.createReview({
              owner: 'cornell-dti',
              repo: 'samwise',
              pull_number: ${{ github.event.number }},
              event: 'COMMENT',
              body: 'Deployed to https://staging-pr.samwise.today/${{ github.event.number }}'
            });
