on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/e2e-course-info.yml
      - frontend/src/assets/json/

name: 'E2E Course Info Consistency'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node 10
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Yarn Install
        run: yarn install
      - name: Produce JSON
        run: |
          cd course-info
          TZ='America/New_York' ./run
      - name: Install JQ for JSON Normalization
        run: sudo apt-get install jq
      - name: Prettify and Sort JSON
        run: |
          cat course-info/sp20-courses-with-exams-min.json | jq 'sort_by(.courseNumber)' > a.json
          cat frontend/src/assets/json/sp20-courses-with-exams-min.json | jq 'sort_by(.courseNumber)' > b.json
      - name: Compare JSON against current JSON
        run: diff a.json b.json
      - name: Automatically create commit if JSON is different
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
        if: failure()
        run: |
          git config --global user.name "dti-github-bot"
          git config --global user.email "admin@cornelldti.org"
          ORIGIN="https://x-access-token:$BOT_TOKEN@github.com/cornell-dti/samwise.git"
          BRANCH="dti-github-bot/update-course-json"
          rm a.json b.json
          cp course-info/sp20-courses-with-exams-min.json frontend/src/assets/json/
          git add .
          git checkout -b "$BRANCH"
          git commit -m "[course-info][bot] Automatically update course JSON"
          git push "$ORIGIN" "$BRANCH" || git push --set-upstream "$ORIGIN" "$BRANCH"
      # Compare this against so that the later step can use the failure status
      - name: Compare JSON against current JSON
        run: diff a.json b.json
      - name: Comment on Pull Request
        uses: actions/github-script@0.2.0
        if: failure()
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            try {
              github.pulls.create({
                owner: 'cornell-dti',
                repo: 'samwise',
                title: '[course-info][bot] Automatically update course JSON',
                head: 'master',
                base: 'dti-github-bot/update-course-json'
              });
            } catch (error) {
              console.error(error);
              console.error('Maybe the PR with the same branch is already created?');
            }
