on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/e2e-course-info.yml

name: 'E2E Course Info Consistency'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node 10
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Yarn Install
        run: yarn install
      - name: Produce JSON
        run: cd course-info && ./run
      - name: Install JQ for JSON Normalization
        run: sudo apt-get install jq
      - name: Prettify and Sort JSON
        run: |
          cat course-info/sp20-courses-with-exams-min.json | jq 'sort_by(.courseNumber)' > a.json
          cat frontend/src/assets/json/sp20-courses-with-exams-min.json | jq 'sort_by(.courseNumber)' > b.json
      - name: Compare JSON against current JSON
        run: diff a.json b.json
