on:
  schedule:
    - cron: '0 19 * * 6'
  pull_request:
    paths:
      - .github/workflows/e2e-course-info.yml
      - frontend/src/assets/json/
      - course-info/*

name: 'E2E Course Info Consistency'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Produce JSON and create PR if necessary
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: TZ='America/New_York' yarn workspace course-info fetch
