name: Release
on: push

jobs:
  check-base-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fail if base-ref is not master
        if: github.base_ref != 'master'
        run: |
          echo "Base ref must be master. Everything should go through staging first!"
          echo "Your base ref is ${{github.base_ref}}."
          exit 1
